// The Tao Te Ching
// by Laozi
// Translation by Stephen Mitchell

var passages = [
"The tao that can be told is not the eternal Tao",
"The name that can be named is not the eternal Name.",
"The unnamable is the eternally real.",
"Naming is the origin of all particular things.",
"Free from desire, you realize the mystery.",
"Caught in desire, you see only the manifestations.",
"Yet mystery and manifestations arise from the same source. This source is called darkness.",
"Darkness within darkness. The gateway to all understanding.",
"When people see some things as beautiful, other things become ugly.",
"When people see some things as good, other things become bad.",
"Being and non-being create each other.",
"Difficult and easy support each other.",
"Long and short define each other.",
"High and low depend on each other.",
"Before and after follow each other.",
"Therefore the Master acts without doing anything and teaches without saying anything.",
"Things arise and she lets them come; things disappear and she lets them go.",
"She has but doesn't possess, acts but doesn't expect.",
"When her work is done, she forgets it. That is why it lasts forever.",
"If you overesteem great men, people become powerless.",
"If you overvalue possessions, people begin to steal.",
"The Master leads by emptying people's minds and filling their cores, by weakening their ambition and toughening their resolve.",
"He helps people lose everything they know, everything they desire, and creates confusion in those who think that they know.",
"Practice not-doing, and everything will fall into place.",
"The Tao is like a well: used but never used up.",
"It is like the eternal void: filled with infinite possibilities.",
"It is hidden but always present.",
"I don't know who gave birth to it. It is older than God.",
"The Tao doesn't take sides; it gives birth to both good and evil.",
"The Master doesn't take sides; she welcomes both saints and sinners.",
"The Tao is like a bellows: it is empty yet infinitely capable.",
"The more you use it, the more it produces;",
"the more you talk of it, the less you understand.",
"Hold on to the center.",
"The Tao is called the Great Mother: empty yet inexhaustible, it gives birth to infinite worlds.",
"It is always present within you. You can use it any way you want.",
"The Tao is infinite, eternal.",
"Why is it eternal? It was never born; thus it can never die.",
"Why is it infinite? It has no desires for itself; thus it is present for all beings.",
"The Master stays behind; that is why she is ahead.",
"She is detached from all things; that is why she is one with them.",
"Because she has let go of herself, she is perfectly fulfilled.",
"The supreme good is like water, which nourishes all things without trying to.",
"It is content with the low places that people disdain. Thus it is like the Tao.",
"In dwelling, live close to the ground.",
"In thinking, keep to the simple.",
"In conflict, be fair and generous.",
"In governing, don't try to control.",
"In work, do what you enjoy.",
"In family life, be completely present.",
"When you are content to be simply yourself and don't compare or compete, everybody will respect you.",
"Fill your bowl to the brim and it will spill.",
"Keep sharpening your knife and it will blunt.",
"Chase after money and security and your heart will never unclench.",
"Care about people's approval and you will be their prisoner.",
"Do your work, then step back. The only path to serenity.",
"Can you coax your mind from its wandering and keep to the original oneness?",
"Can you let your body become supple as a newborn child's?",
"Can you cleanse your inner vision until you see nothing but the light?",
"Can you love people and lead them without imposing your will?",
"Can you deal with the most vital matters by letting events take their course?",
"Can you step back from you own mind and thus understand all things?",
"Giving birth and nourishing, having without possessing, acting with no expectations, leading and not trying to control: this is the supreme virtue.",
"We join spokes together in a wheel, but it is the center hole that makes the wagon move.",
"We shape clay into a pot, but it is the emptiness inside that holds whatever we want.",
"We hammer wood for a house, but it is the inner space that makes it livable.",
"We work with being, but non-being is what we use.",
"Colors blind the eye.",
"Sounds deafen the ear.",
"Flavors numb the taste.",
"Thoughts weaken the mind.",
"Desires wither the heart.",
"The Master observes the world but trusts his inner vision.",
"He allows things to come and go. His heart is open as the sky.",
"Success is as dangerous as failure.",
"Hope is as hollow as fear.",
"What does it mean that success is a dangerous as failure? Whether you go up the ladder or down it, you position is shaky.",
"When you stand with your two feet on the ground, you will always keep your balance.",
"What does it mean that hope is as hollow as fear? Hope and fear are both phantoms that arise from thinking of the self.",
"When we don't see the self as self, what do we have to fear?",
"See the world as your self.",
"Have faith in the way things are.",
"Love the world as your self; then you can care for all things.",
"Look, and it can't be seen.",
"Listen, and it can't be heard.",
"Reach, and it can't be grasped.",
"Above, it isn't bright. Below, it isn't dark.",
"Seamless, unnamable, it returns to the realm of nothing.",
"Form that includes all forms, image without an image, subtle, beyond all conception.",
"Approach it and there is no beginning; follow it and there is no end.",
"You can't know it, but you can be it, at ease in your own life.",
"Just realize where you come from: this is the essence of wisdom.",
"The ancient Masters were profound and subtle. Their wisdom was unfathomable.",
"There is no way to describe it; all we can describe is their appearance.",
"Do you have the patience to wait till your mud settles and the water is clear?",
"Can you remain unmoving till the right action arises by itself?",
"The Master doesn't seek fulfillment.",
"Not seeking, not expecting, she is present, and can welcome all things.",
"Empty your mind of all thoughts. Let your heart be at peace.",
"Watch the turmoil of beings, but contemplate their return.",
"Each separate being in the universe returns to the common source. Returning to the source is serenity.",
"If you don't realize the source, you stumble in confusion and sorrow.",
"When you realize where you come from, you naturally become tolerant, disinterested, amused, kindhearted as a grandmother, dignified as a king.",
"Immersed in the wonder of the Tao, you can deal with whatever life brings you, and when death comes, you are ready.",
"When the Master governs, the peopleare hardly aware that he exists.",
"Next best is a leader who is loved. Next, one who is feared. The worst is one who is despised.",
"If you don't trust the people, you make them untrustworthy.",
"The Master doesn't talk, he acts. When his work is done, the people say, 'Amazing: we did it, all by ourselves!'",
"When the great Tao is forgotten, goodness and piety appear.",
"When the body's intelligence declines, cleverness and knowledge step forth.",
"When there is no peace in the family, filial piety begins.",
"When the country falls into chaos, patriotism is born.",
"Throw away holiness and wisdom, and people will be a hundred times happier.",
"Throw away morality and justice, and people will do the right thing.",
"Throw away industry and profit, and there won't be any thieves.",
"Stop thinking, and end your problems.",
"What difference between yes and no? What difference between success and failure? Must you value what others value, avoid what others avoid?",
"I alone don't care, I alone am expressionless, like an infant before it can smile.",
"Other people have what they need; I alone possess nothing.",
"I alone drift about, like someone without a home.",
"I am like an idiot, my mind is so empty.",
"Other people are bright; I alone am dark.",
"Other people are sharper; I alone am dull.",
"Other people have a purpose; I alone don't know.",
"I drift like a wave on the ocean, I blow as aimless as the wind.",
"The Master keeps her mind always at one with the Tao; that is what gives her her radiance.",
"The Tao is ungraspable.",
"How can her mind be at one with it? Because she doesn't cling to ideas.",
"The Tao is dark and unfathomable. How can it make her radiant? Because she lets it.",
"Since before time and space were, the Tao is.",
"It is beyond is and is not. How do I know this is true? I look inside myself and see.",
"If you want to become whole, let yourself be partial.",
"If you want to become straight, let yourself be crooked.",
"If you want to become full, let yourself be empty.",
"If you want to be reborn, let yourself die.",
"If you want to be given everything, give everything up.",
"The Master, by residing in the Tao, sets an example for all beings.",
"Because he doesn't display himself, people can see his light.",
"Because he has nothing to prove, people can trust his words.",
"Because he doesn't know who he is, people recognize themselves in him.",
"Because he has no goad in mind, everything he does succeeds.",
"When the ancient Masters said, 'If you want to be given everything, give everything up,' they weren't using empty phrases.",
"Only in being lived by the Tao can you be truly yourself.",
"Express yourself completely, then keep quiet.",
"Be like the forces of nature: when it blows, there is only wind; when it rains, there is only rain; when the clouds pass, the sun shines through.",
"If you open yourself to the Tao, you are at one with the Tao and you can embody it completely.",
"If you open yourself to insight, you are at one with insight and you can use it completely.",
"If you open yourself to loss, you are at one with loss and you can accept it completely.",
"Open yourself to the Tao, then trust your natural responses; and everything will fall into place.",
"He who stands on tiptoe doesn't stand form.",
"He who rushes ahead doesn't go far.",
"He who tries to shine dims his own light.",
"He who defines himself can't know who he really is.",
"He who has power over others can't empower himself.",
"He who clings to his work will create nothing that endures.",
"If you want to accord with the Tao, just do your job, then let go.",
"There was something formless and perfect before the universe was born.",
"It is serene. Empty. Solitary. Unchanging. Infinite. Eternally present.",
"It is the mother of the universe.",
"For lack of a better name, I call it the Tao.",
"It flows through all things, inside and outside, and returns to the origin of all things.",
"The Tao is great.",
"The universe is great.",
"Earth is great.",
"Man is great.",
"These are the four great powers.",
"Man follows the earth.",
"Earth follows the universe.",
"The universe follows the Tao.",
"The Tao follows only itself.",
"The heavy is the root of the light.",
"The unmoved is the source of all movement.",
"Thus the Master travels all day without leaving home.",
"However splendid the views, she stays serenely in herself.",
"Why should the lord of the country flit about like a fool?",
"If you let yourself be blown to and fro, you lose touch with your root.",
"If you let restlessness move you, you lose touch with who you are.",
"A good traveler has no fixed plans and is not intent upon arriving.",
"A good artist lets his intuition lead him wherever it wants.",
"A good scientist has freed himself of concepts and keeps his mind open to what is.",
"Thus the Master is available to all people and doesn't reject anyone.",
"He is ready to use all situations and doesn't waste anything. This is called embodying the light.",
"What is a good man but a bad man's teacher? What is a bad man but a good man's job?",
"If you don't understand this, you will get lost, however intelligent you are.",
"It is the great secret.",
"Know the male, yet keep to the female: receive the world in your arms.",
"If you receive the world, the Tao will never leave you and you will be like a little child.",
"Know the white, yet keep to the black: be a pattern for the world.",
"If you are a pattern for the world, the Tao will be strong inside you and there will be nothing you can't do.",
"Know the personal, yet keep to the impersonal: accept the world as it is.",
"If you accept the world, the Tao will be luminous inside you and you will return to your primal self.",
"The world is formed from the void, like utensils from a block of wood.",
"The Master knows the utensils, yet keeps to the the block: thus she can use all things.",
"Do you want to improve the world? I don't think it can be done.",
"The world is sacred. It can't be improved.",
"If you tamper with it, you'll ruin it.",
"If you treat it like an object, you'll lose it.",
"There is a time for being ahead, a time for being behind; a time for being in motion, a time for being at rest; a time for being vigorous, a time for being exhausted; a time for being safe, a time for being in danger.",
"The Master sees things as they are, without trying to control them.",
"She lets them go their own way, and resides at the center of the circle.",
"Whoever relies on the Tao in governing men doesn't try to force issues or defeat enemies by force of arms.",
"For every force there is a counterforce.",
"Violence, even well intentioned, always rebounds upon oneself.",
];

window.onload = function() {
  var passage = passages[Math.floor(Math.random() * passages.length)];
  var tao = document.getElementById('tao');
  tao.insertAdjacentHTML('afterbegin', '<p>' + passage + '</p>');
}